'''
Interfaces for the package that agencies can subclass.
This allows each agency to be handled mostly the same way, rather than having
tons of hardcoded exceptions and idiosyncrasies all over the place.
'''

from abc import ABC, abstractmethod
from json import dumps
import os
import re
from datetime import datetime

# These two constants are imported for Pierce Transit and Everett Transit routes
# Though they could be, they're not used for other agencies
# This is because they're less accurate and well-maintained as a source
TP_REQ = ('tripplanner.kingcounty.gov/TI_FixedRoute_Line', dumps(
    {'version': '1.1', 'method': 'GetLines'}))
TP_PATTERN = re.compile(r'.*(?:[Tt]o|-) (.*?)(?: via .*)?')
# This will allow all widely-supported raster image formats while disallowing
# most other files incidentally present
SHORT_FILENAME_PATTERN = re.compile(r'\*?([\w\d]*)\.[abefgijnpvw]+')
TIME_FORMAT = '%-m/%-d/%y %-H:%M'
# This is for RouteListings to export their own HTML, in to_html()
EXISTENCE_NOTES = (
    ('discontinued', 'Discontinued'), ('none', ''), ('delisted', 'Delisted'))
TABLE_HTML = '    <table>\n%s\n    </table>'
ROW_HTML = '%s<tr>%s</tr>' % (' ' * 6, '%s' * 6)
IMG_HTML = '<img src="%s" alt="%s" title="%s" width=100></img>'

class DataParserInterface(ABC):
    '''
    Handles the gathering of data for each particular agency implementing it.
    Creates and manages RouteListings.
    '''
    def __init__(self, agency, image_dir=None):
        '''
        Initializes attributes and RouteListings of self.
        Parameter string image_dir will be the directory in which this agency's
        image files will be found.
        '''
        self.agency = agency
        # We need this for generating HTML
        if image_dir:
            self.image_dir = os.path.join(image_dir, agency)
            self.images = os.listdir(self.image_dir)
        else:
            self.image_dir = None
            self.images = []
        # Dictionary will have numbers (agency-specific) as keys, and
        # RouteListings as values
        self.routelistings = dict()
        for i in self.images:
            match = SHORT_FILENAME_PATTERN.match(i)
            try:
                # Get the RouteListing class (agency-specific), and instantiate
                rl = self.get_route_listing_class()(match.group(1))
                if i.startswith('*'):
                    rl.existence = 2
                rl.img = os.path.join(self.image_dir, i)
                secs = os.stat(rl.img).st_birthtime
                rl.datetime = datetime.fromtimestamp(secs).strftime(TIME_FORMAT)
                self.routelistings[rl.number] = rl
            # This can fail because match is None, or AttributeError is raised
            # by rl.__init__
            except AttributeError:
                continue

    @abstractmethod
    def get_route_listing_class(self):
        '''
        This method returns the RouteListing class specific to the agency
        implementing this interface. This is needed so this interface code can
        instantiate them properly.
        '''
        pass

    @abstractmethod
    def get_initial_requests(self):
        '''
        This method returns a set whose contents are either strings (URIs
        preceded by DNS names, i.e. website URLs) for GET requests, or tuples
        containing a string URL and a request body for POST requests.
        These are provided to http.client.HTTPSConnection.request,
        though an invariant headers field is added.
        After this first step is handled by main program (because some
        agencies might share resources), DataParsers are free to request
        resources on their own.
        '''
        pass

    @abstractmethod
    def update(self, resources):
        '''
        This function takes a dictionary whose keys are either strings (URIs
        preceded by DNS names, i.e. website URLs) for GET requests, or tuples
        containing a string URL and a request body for POST requests, and whose
        values are what is returned by the server.
        Internal RouteListings are updated using the contents of these.
        DataParsers may request resources on their own in this function.
        '''
        pass

    def completed(self):
        '''
        Returns two integers: the number of total existing routes in
        self.routelistings, and the number of those which are completed.
        '''
        total = 0
        completed = 0
        for rl in self.routelistings.values():
            if rl.existence:
                total += 1
                if rl.img:
                    completed += 1
        return total, completed

    def to_html(self, verbose):
        '''
        Returns HTML generated by this DataParser, which will be composed of
        a header and a table made of HTML rows generated by RouteListings in
        self.routelistings.
        If verbose is True, prints messages to stdout.
        '''
        if verbose:
            print('Sorting %s listings...' % self.agency, end='', flush=True)
        listings = sorted(self.routelistings.values())
        if verbose:
            print('Done')
            for l in listings:
                print(l)
        return TABLE_HTML % '\n'.join(l.to_html() for l in listings)

class RouteListingInterface(ABC):
    '''
    Classes implementing this interface allows for easier management of
    table rows and their associated data and images.
    '''
    @abstractmethod
    def __init__(self, short_filename=None):
        '''
        Initializes self from most of an image's filename (just not the leading
        * or file extension), a process which might differ depending on the
        agency. Does not initialize all attributes to proper values yet.
        Raises AttributeError on failure; object should not be used after this.
        self.agency, self.number, and self.css_class (at least) must be set by
        overriding method.
        '''
        self.position = self.position()
        # These attributes are all default values, set later on if applicable
        self.start = ''
        self.dest = ''
        self.links = (None, None, None)
        # Python doesn't have C-style enums, so 0 = discontinued, 1 = normal,
        # 2 = delisted
        if not hasattr(self, 'existence'):
            self.existence = 0
        self.datetime = 'Incomplete'
        self.img = None

    def __str__(self):
        '''Returns string representation of self, for debugging or -v.'''
        return ' '.join((
            'i–'[not self.img] + '! *'[self.existence],
            self.agency,
            self.number,
            '(' + self.css_class + ')',
            self.start,
            '⬌',
            self.dest))

    def __lt__(self, other):
        '''
        Returns whether self is less than RouteListing other, for purposes of
        comparison. Only valid within this agency.
        '''
        return self.position < other.position

    def position(self):
        '''
        Sets position value relative to other RouteListings from this agency.
        This is used for comparisons. Default may be commonly used, but if any
        route for this agency has a non-numeric name, it will need overriding.
        '''
        # This will cause ValueError on failure, indicating need for overriding
        return int(self.number)

    def set_links(self, linkbase, linkpiece, linkoptions):
        '''
        Sets tuple self.links to string linkbase formatted with string linkpiece
        and each of the strings in tuple linkoptions.
        This allows each td in this RouteListing's tr to have a different but
        related link.
        '''
        self.links = tuple(linkbase % (linkpiece, o) for o in linkoptions)

    def to_html(self):
        '''
        Returns this row's <tr> HTML element for the final table.
        This isn't the most elegant way to handle CSS classes when writing HTML
        by hand, but it is more simple when generating it.
        Handles special cases for visuals.
        '''
        # More notes may be needed in the future
        note = EXISTENCE_NOTES[self.existence]
        if self.img:
            i_link = self.img
            i_td = td(
                'none',
                IMG_HTML % (i_link, self.number, self.number),
                i_link,
                False)
        else:
            i_td = td('none', '')
        full_css_class = self.agency + '-' + self.css_class
        return ROW_HTML % (
            td('b-' + full_css_class, self.displaynum(), self.links[0]),
            td('n-' + full_css_class, self.start, self.links[1]),
            td('n-' + full_css_class, self.dest, self.links[2]),
            td(*note),
            td('complete' if self.img else 'incomplete', self.datetime),
            i_td)

    def displaynum(self):
        '''
        Returns this RouteListing's HTML number, which could be the simple
        number in plaintext or contain more complicated HTML.
        This will almost always be overridden.
        '''
        return self.number

def td(css_class, data, link=None, blank=True):
    '''
    Returns <td> HTML element given css_class, text/image data, and link.
    If link should open in same tab, blank should be False.
    '''
    if not link:
        return '<td class="%s">%s</td>' % (css_class, data)
    if blank:
        jsfunc = 'window.open(\'%s\', \'_blank\')' % link
    else:
        jsfunc = 'window.open(\'%s\', \'_self\')' % link
    return '<td class="%s" onclick="%s">%s</td>'\
        % (css_class, jsfunc, data)
